### ISSUE TITLE
What should the welcome bot say?

### ISSUE THREAD

**Issue by emmairwin** [maintainercohort/cohort-repo#13]
What 3 things should every new community member know they can do, to get started with Debugger?
We can add this to Bot proposal :  https://github.com/maintainercohort/cohort-repo/issues/12

Related to #12

**Comment by reCursedd** [comment]
1. They should be aware of what the debugger does. - a small introduction of Mozilla debugger 
2. They should be introduced to all the other developer and community channel or mailing list the debugger is associated with. - They might have some other purpose and might want to join other channels. 
3. They should be redirected to the Github readme file and also 'easy' or 'good-for-beginners' tasks.

**Comment by princiya** [comment]
A very inclusive message I found today

https://twitter.com/stefanjudis/status/1072066478114070529

<img width="1374" alt="screenshot 2018-12-10 at 12 31 48" src="https://user-images.githubusercontent.com/8022693/49730100-9cfe0100-fc77-11e8-98c1-003ba3900223.png">

**Comment by emmairwin** [comment]
duplicate of #12 lets keep all convesation there.
